spring:
  profiles.active: dohko
---
spring:
  profiles: dohko
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  kafka:
    bootstrap-servers: 172.16.0.30:9092,172.16.0.31:9092,172.16.0.32:9092
    #    bootstrap-servers: 172.16.0.30:9092,172.16.0.31:9092,172.16.0.32:9092
#    bootstrap-servers: 172.16.32.250:9092,172.16.32.248:9092,172.16.32.83:9092
    listener:
      concurrency: 3
    consumer:
      group-id: sassPosDeviceManageServiceGroup
      timeOut : 60000
      time:
          ms: 500
      interval:
          ms : 2000
    template:
      default-topic: bd_canal_passport


server:
  port: 8082
